language: node_js

node_js:
  - '12'
  - '10'
  - '8'

os:
  - linux
  - osx
  - windows

install:
  - npm install --ignore-scripts

script:
  - npm test

sudo: enabled

jobs:
  fast_finish: true

  include:

    # Nightlies
    - stage: Node.js pre-releases
      node_js: '12'
      if: type = cron
      env: NVM_NODEJS_ORG_MIRROR=https://nodejs.org/download/nightly/
    -
      node_js: '11'
      if: type = cron
      env: NVM_NODEJS_ORG_MIRROR=https://nodejs.org/download/nightly/
    -
      node_js: '10'
      if: type = cron
      env: NVM_NODEJS_ORG_MIRROR=https://nodejs.org/download/nightly/
    -
      node_js: '8'
      if: type = cron
      env: NVM_NODEJS_ORG_MIRROR=https://nodejs.org/download/nightly/

    # Release Candidates
    -
      node_js: '12'
      if: type = cron
      env: NVM_NODEJS_ORG_MIRROR=https://nodejs.org/download/rc/
    -
      node_js: '11'
      if: type = cron
      env: NVM_NODEJS_ORG_MIRROR=https://nodejs.org/download/rc/
    -
      node_js: '10'
      if: type = cron
      env: NVM_NODEJS_ORG_MIRROR=https://nodejs.org/download/rc/
    -
      node_js: '8'
      if: type = cron
      env: NVM_NODEJS_ORG_MIRROR=https://nodejs.org/download/rc/


notifications:
  email:
    - post@trygve-lie.com